name = "ui-api-mcp"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "52b1c60ff2a24fb21c1ef9a429e63261"

[dev]
port = 8788

[vars]
UI_API_BASE = "https://api.ui.com"
